# Generated by Django 4.2.7 on 2023-11-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='Слаг'),
        ),
    ]
