# Generated by Django 4.2.7 on 2023-11-30 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proglang',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программиирования'},
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, help_text='*Необязательно', null=True, verbose_name='Примеры и доп. описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
